In [2]:
level = {
    'intern': {
        'bonus': 5
    },
    'staff': {
        'bonus': 10
    },
    'manager': {
        'bonus': 15
    },
    'director': {
        'bonus': 20
    }
}

employee_data = [
    {
        'name': 'Rudi',
        'level': 'staff',
        'salary': 7500000
    },
    {
        'name': 'Rita',
        'level': 'intern',
        'salary': 1000000
    },
    {
        'name': 'Asep',
        'level': 'manager',
        'salary': 12000000
    },
    {
        'name': 'Ricky',
        'level': 'manager',
        'salary': 13500000
    },
    {
        'name': 'Lisa',
        'level': 'staff',
        'salary': 8500000
    },
    {
        'name': 'Imam',
        'level': 'intern',
        'salary': 1050000
    },
    {
        'name': 'Haryo',
        'level': 'director',
        'salary': 35000000
    }
]

In [ ]:
# expected result
# based on level
# bonus = salary * bonus/100

# employee_bonus = { 
#     'Rudi': 750000,
#     'Rita': 50000
#     ...
# }

In [3]:
# Data level dan bonus
level = {
    'intern': {
        'bonus': 5
    },
    'staff': {
        'bonus': 10
    },
    'manager': {
        'bonus': 15
    },
    'director': {
        'bonus': 20
    }
}

# Data karyawan
employee_data = [
    {
        'name': 'Rudi',
        'level': 'staff',
        'salary': 7500000
    },
    {
        'name': 'Rita',
        'level': 'intern',
        'salary': 1000000
    },
    {
        'name': 'Asep',
        'level': 'manager',
        'salary': 12000000
    },
    {
        'name': 'Ricky',
        'level': 'manager',
        'salary': 13500000
    },
    {
        'name': 'Lisa',
        'level': 'staff',
        'salary': 8500000
    },
    {
        'name': 'Imam',
        'level': 'intern',
        'salary': 1050000
    },
    {
        'name': 'Haryo',
        'level': 'director',
        'salary': 35000000
    }
]

# Menghitung bonus berdasarkan level
employee_bonus = {}
for employee in employee_data:
    level_bonus = level[employee['level']]['bonus']
    bonus_amount = employee['salary'] * (level_bonus / 100)
    employee_bonus[employee['name']] = bonus_amount

# Menampilkan hasil
print(employee_bonus)

{'Rudi': 750000.0, 'Rita': 50000.0, 'Asep': 1800000.0, 'Ricky': 2025000.0, 'Lisa': 850000.0, 'Imam': 52500.0, 'Haryo': 7000000.0}